package ex02;

import java.util.Scanner;

public class ExceptionEx01 {
	public static void main(String[] args) {
		System.out.println("예외처리1");
		System.out.println("예외처리2");
		System.out.println("예외처리3");
		System.out.println("예외처리4");
		
		Scanner sc = new Scanner(System.in);
		System.out.println("정수입력 (0은 입력하지 마세요)");
		try { //예외발생할곳 넣어줌
			int num = sc.nextInt(); //정수입력이 아니면 오류발생!
			System.out.println(5/num); //0을 입력하면 오류발생!			
		} catch (Exception e) {
		}
		System.out.println("예외처리5");
		System.out.println("예외처리6");
		System.out.println("예외처리7");
		System.out.println("예외처리8");
		System.out.println("프로그램 종료!!");
	}
}
